### ISSUE TITLE
While choosing a pin for the first time, closing and restarting the app bypasses this. Allowing the user access to the app without pin code.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/3Bot_connect#10]
**Repro steps**
1) Register a new account
2) Close app while picking a pin
3) Restart App

**Expected Result**
User has to pick a pin before continuing

**Actual Result**
User gains access to the app without having a pin

**System Info**
Type: Staging 
Git hash: be307eb 
Time: 2020.01.07-14.27.57 
Size: 24883962 
MD5: b9af2e939d61ee43574c73b5579299a1

**Comment by MathiasDeWeerdt** [comment]
The user can visit the settings page and set a new pincode when there's no pincode set.

**Comment by ken-de-moor** [comment]
Not a good enough solution, app should prompt for pincode when it's not set upon first opening. Changed prio to low though.
