### ISSUE TITLE
Wallet fails to load on Android 5.0.2

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/3Bot_connect#104]
**Repro steps**
1) Open wallet on android 5.0.2

**Expected Result**
Wallet works, If this is a limitation of android versions that is not fixable, then we should ensure the play store does not say we support version 5 and higher, but bump it up a version.

**Actual Result**
![image](https://user-images.githubusercontent.com/59569757/84369882-d0587d80-abd7-11ea-911c-c442961c8a5b.png)

**System Info**

**Comment by MathiasDeWeerdt** [comment]
Minimum support android version is 5.1 or 6.0, would need to double check but 5.0.2 is not supported. Might need to bump the API level to 22 when compiling the app to prevent it from showing up in the playstore.
