### ISSUE TITLE
Social - After creating a new space, user can't post on this space as there is no submit button.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/3Bot_connect#12]
**Repro steps**
1) Create new space
2) Try to post something in the "what's on your mind"

**Expected Result**
Possible to post

**Actual Result**
Impossible to post until the user navigates away from the space and back, the submit button does not appear.

**System Info**
Type: Staging 
Git hash: caa24a9 
Time: 2020.01.07-16.53.17 
Size: 24888734 
MD5: bb1e1f6cb79309e795117579669fc323

**Comment by MathiasDeWeerdt** [comment]
This issue should be redirected to @Hamdy and moved to the correct github project.

**Comment by ken-de-moor** [comment]
> This issue should be redirected to @Hamdy and moved to the correct github project.

The issue does not happen in chrome or mobile, only in our implementation of the webview.
