### ISSUE TITLE
fingerprint / face unlock on same version 2.0.0 - 99

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/3Bot_connect#143]
Here's on my phone honor 8x (android 10)
![image](https://user-images.githubusercontent.com/64129/93688114-bb876200-fac3-11ea-9a18-b2769ba64ec1.png)

and on another phone xiaomi redmi k20 pro (android 10)
![image](https://user-images.githubusercontent.com/64129/93688121-c80bba80-fac3-11ea-801d-5f182a5e0e9f.png)

or does it happen the string versions rendered aren't bumped?

**Comment by ken-de-moor** [comment]
The strings are rendered based on what your phone actually supports. So it's different based on OS version and apple vs android also.
