### ISSUE TITLE
3bot connect still shows up on the website

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/3Bot_connect#160]
![image](https://user-images.githubusercontent.com/64129/99566954-38588e80-29d6-11eb-8bcc-3b3e554e216a.png)

**Comment by sasha-astiadi** [comment]
this issue is promoted to bigger issue a a part of tf connect 2.2  https://github.com/threefoldtech/3Bot_connect/issues/162

**Comment by xmonader** [comment]
reopened as agreed to have this fix now for consistency of 2.3
