### ISSUE TITLE
login.threefold.me rebranding

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/3Bot_connect#162]
assets:

FIGMA: https://www.figma.com/file/8Clg1VE7MfwBGv8dMfO7wJ/3bot-website-drafts?node-

- [x] Change the background image 
[background-tf.jpg.zip](https://github.com/threefoldtech/3Bot_connect/files/5582993/background-tf.jpg.zip)

- [x] change the bar bg color into tf blue

- [x] change the overlay bg color into tf blue

- [x] change the button color into tf green

- [x] change the wording instructions / ux writing

**Comment by JonasWijne** [comment]
@sasha-astiadi, I have implemented al previous changes, can you check the figma i added some screens
