### ISSUE TITLE
Payment problem for reservations made  on testnet

### ISSUE THREAD

**Issue by manishautomatic** [threefoldtech/3Bot_connect#165]
For making payments on deployment made on `https://deploy3bot.testnet.grid.tf/threebot_deployer/#/` , the 3bot_connect app gives `destination account does not exists ` error.

Please refer the following screen recording `https://youtu.be/dnpBIZtSjtc`

**Comment by xmonader** [comment]
I checked the screen recording again, it seems you're using the 3bot connect app (for mainnet) and trying to pay on testnet with it?
