### ISSUE TITLE
Register account through app has no 50 character limit for account name, while the website does.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/3Bot_connect#22]
**Repro steps**
1) Register on the app, using a very long account name
2) Finish the registration

**Expected Result**
Unable to enter an account name longer than 50.

**Actual Result**
Will give issues for really long names, for example when verifying the account this is done through a URL parameter.

![image](https://user-images.githubusercontent.com/59569757/72245370-b434be00-35f0-11ea-8e1b-abaeac6f9451.png)

**System Info**
Type: Local 
Git user: Mathias De Weerdt 
Git hash: ff7ec3e 
Time: 10:26:15 13.01.2020 
Message:

**Comment by MathiasDeWeerdt** [comment]
Added validation inside the app. The backend now also enforces this behavior.

**Comment by ken-de-moor** [comment]
app validation has 100 max length, backend throws error as a result.

Please update the 100 limit in app to 50.

**Comment by azertyalex** [comment]
@MathiasDeWeerdt

**Comment by MathiasDeWeerdt** [comment]
Changed to 50.
