### ISSUE TITLE
Possible to show a crash screen to any user by sending invalid websocket data.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/3Bot_connect#26]
**Repro steps**
1) On the login flow, resend websocket data but change image ID to 1+1 instead of whatever int it was before.
2) Check the app

**Expected Result**
Nothing, invalid websocket requests should be blocked by the server.

**Actual Result**
![image](https://user-images.githubusercontent.com/59569757/72258415-53b47980-360e-11ea-8fb2-f28e98d0c486.png)

**System Info**
Type: Staging 
Git hash: 5018819 
Time: 2020.01.13-10.57.19 
Size: 24972480 
MD5: 8202d83e03ada3a1754900fe6a663dda

**Comment by MathiasDeWeerdt** [comment]
Can this be retested?
