### ISSUE TITLE
When refreshing on the emoji(resend notification) page, the login flow breaks.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/3Bot_connect#36]
**Repro steps**
1) Go to freeflowpages and login
2) Fill in an existing user
3) On the resend notification page, press refresh
4) Fill in the existing user again, fill in pin and select emoji

**Expected Result**
User is logged in correctly, either through redirecting to the first step of the login or by passing the URL parameters to the final step, rather than stripping them.

**Actual Result**
Null would like to access, login fails.

**System Info**
ADDITIONAL INFORMATION
Updated
January 13, 2020
Size
4.0M
Installs
500+
Current Version
1.4.2
Requires Android
5.0 and up

**Comment by MathiasDeWeerdt** [comment]
Now redirects to error page.
