### ISSUE TITLE
When using the back button after a failed login to return to the "Identify yourself" page, the login flow breaks after.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/3Bot_connect#37]
**Repro steps**
1) Go to freeflow pages and log in
2) Fill in an existing account
3) On the app, say it wasn't me
4) After receiving the error, use the back button on the browser
5) Repeat the login flow

**Expected Result**
The login flow works, either by redirecting the user to the first step again, or by passing the correct URL parameters on refresh/back.

**Actual Result**
Null would like to access, login fails.

**System Info**
ADDITIONAL INFORMATION
Updated
January 13, 2020
Size
4.0M
Installs
500+
Current Version
1.4.2
Requires Android
5.0 and up

**Comment by MathiasDeWeerdt** [comment]
Now redirects to an error page.
