### ISSUE TITLE
After recovering an account, the email becomes unverified.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/3Bot_connect#38]
**Repro steps**
1) Recover an account that has a verified email
2) Check if the email is still verified

**Expected Result**
Email is still verified

**Actual Result**
Email is no longer verified

**System Info**
Updated
January 13, 2020
Size
4.0M
Installs
500+
Current Version
1.4.2
Requires Android
5.0 and up

**Comment by MathiasDeWeerdt** [comment]
This is by design, the object the represents that the user his email has been validated is kept on the device. Recovering the account means that the user needs to re-validate his or her email.
