### ISSUE TITLE
It should be possible to change the email used in 3bot.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/3Bot_connect#39]
Several scenarios where this is an important feature.

1) User changes their actual email because their old email will become inaccessible in the future.
2) User first signed up using a junk mail, not realizing confirmation of the email is actually required for certain functionality. Many Tech savvy users will use fake mails at first, if there is no option to change this email after they will likely not bother to recreate an account and simply uninstall the app.

**Comment by MathiasDeWeerdt** [comment]
This is currently possible through the recovery flow.

**Comment by MathiasDeWeerdt** [comment]
This story changed with the integration of the explorerDB phonebook.
