### ISSUE TITLE
When recovering an account, any email can be used.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/3Bot_connect#40]
**Repro steps**
1) Recover an account
2) Use another email to recover this account

**Expected Result**
Fails to recover, all data should be correct. Doublename, mail, and seed phrase.

**Actual Result**
Recovers, and changes email.

**System Info**
Updated
January 13, 2020
Size
4.0M
Installs
500+
Current Version
1.4.2
Requires Android
5.0 and up

**Comment by MathiasDeWeerdt** [comment]
This is intentional. A user should be able to change their email and the current process to do this is through the recovery flow.
