### ISSUE TITLE
When the 3bot app is backgrounded, other apps performance is impacted.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/3Bot_connect#41]
**Repro steps**
1) Noticed with VNC Viewer, not sure what other app can be easily used to reproduce.
2) Start 3bot 
3) Background it and start VNC Viewer to open a connection to desktop, notice how choppy the connection is and how dragging it is very slow.
4) Kill the 3bot app and retry VNC Viewer again

**Expected Result**
3bot running backgrounded should have no noticeable impact on other app performance.

**Actual Result**
Very noticeable difference in performance.

**System Info**
Updated
January 13, 2020
Size
4.0M
Installs
500+
Current Version
1.4.2
Requires Android
5.0 and up

**Comment by ken-de-moor** [comment]
Important update: Issue is specifically related to the support page, not opening this page does not cause the performance decrease. The moment this page has been opened once, the issues start.

**Comment by MathiasDeWeerdt** [comment]
This is extremely weird and requires further investigation, currently not able to reproduce this issue.

**Comment by MathiasDeWeerdt** [comment]
Could you test this issue with the support page loaded in chrome and report back @ken-de-moor ?

**Comment by ken-de-moor** [comment]
> Could you test this issue with the support page loaded in chrome and report back @ken-de-moor ?
@MathiasDeWeerdt 

Just tested, issue happens on 3bot app on both prod version and latest staging version.
When using Chrome and browsing to support.grid.tf it doesn't happen at all.
When using Firefox and browsing to support.grid.tf it doesn't happen at all either.

My phone is on android 9 ( Galaxy A50 )

**Comment by MathiasDeWeerdt** [comment]
Still needs more investigation. Issue is still unknown.
