### ISSUE TITLE
Scanning QR on wallet while having the keyboard open does not close the keyboard, after closing keyboard the QR scan fails.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/3Bot_connect#42]
**Repro steps**
1) Go to wallet - send
2) Open keyboard by selecting any of the input fields
3) Scan QR
4) Close keyboard

**Expected Result**
Keyboard should close automatically
Scan QR should remain working

**Actual Result**
Keyboard does not close
Upon closing keyboard, breaks the QR scan (black screen)

**System Info**
Updated
January 13, 2020
Size
4.0M
Installs
500+
Current Version
1.4.2
Requires Android
5.0 and up

**Comment by jdelrue** [comment]
@ken-de-moor please retest should be fixed

**Comment by MathiasDeWeerdt** [comment]
Fixed
