### ISSUE TITLE
Iphone S - Authentication by fingerprint causes layout and performance issues.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/3Bot_connect#46]
**Repro steps**
1) Enable fingerprint on Iphone S
2) Attempt to use fingerprint auth on wallet
3) Attempt to use fingerprint auth on show phrase
4) Attempt to use fingerprint auth on login flow

**Expected Result**
Works in every flow

**Actual Result**
Layout issues in wallet and login flow (split screen)
Performance issues in show phrase ( sometimes takes long to open or doesn't open at all )

**System Info**
Using Iphone S
Version 1.4.3 - 67 TestFlight

**Comment by ken-de-moor** [comment]
Disabling fingerprint authentication again removes all these issues, it's specifically related to fingerprint being enabled.

**Comment by coeneivan** [comment]
![ADACE675-FB44-40D4-B0A8-06341066ABF4_1_105_c](https://user-images.githubusercontent.com/22675385/72529633-fae31c00-386d-11ea-8cb6-42093e215b4f.jpeg)

**Comment by MathiasDeWeerdt** [comment]
Waiting for biometric plugin update, closed for now.

**Comment by ken-de-moor** [comment]
prio changed but re-opened as it's still an issue. Only actual fixed issues should be closed, even when it's impossible to fix them currently.
