### ISSUE TITLE
Freeflowpages login flow still has the 3 steps (old flow)

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/3Bot_connect#51]
**Repro steps**
1) Go to freeflowpages.com in an anonymous browser window 
2) Sign in

**Expected Result**
No 3 steps, only sign in.

**Actual Result**
![image](https://user-images.githubusercontent.com/59569757/72611429-596dd000-392a-11ea-91be-06fec906d56a.png)

**System Info**

**Comment by coeneivan** [comment]
https://github.com/threefoldtech/3Bot_connect/commit/b84228599bc36f7987d9f5da99c0a83ff3a08529

**Comment by MathiasDeWeerdt** [comment]
Fixed by ivan

**Comment by ken-de-moor** [comment]
just testing re-open and close
