### ISSUE TITLE
During the login flow on the emoji page, the help link for recovering your account links to an empty page.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/3Bot_connect#53]
**Repro steps**
1) Go to freeflowpages login
2) On the emoji page, press the help button
3) Click on the recover here link

**Expected Result**
Links to a functioning page

**Actual Result**
Links to an empty page
![8erQ5AGnB3](https://user-images.githubusercontent.com/59569757/72615091-23354e00-3934-11ea-9215-36035c86de81.gif)

**System Info**

**Comment by MathiasDeWeerdt** [comment]
@coeneivan

**Comment by MathiasDeWeerdt** [comment]
Added info
