### ISSUE TITLE
iPhone SE - Multiple layout issue

### ISSUE THREAD

**Issue by maxux** [threefoldtech/3Bot_connect#54]
When using 3bot connect on iPhone SE, there are two layout issue:
- When requesting to « Show Phrase », the pin-pad is a a little bit hidden. It still usable but not right :)
![Show Phrases layout issue](https://i.imgur.com/EvyJlDd.png)

- When we are logged-in, the text should be centered or at least some margin are missing IMO
![Logged In margin missing](https://i.imgur.com/tteqbSP.png)

**Comment by MathiasDeWeerdt** [comment]
The first part is fixed

**Comment by MathiasDeWeerdt** [comment]
Second part is also fixed.
