### ISSUE TITLE
Cleanup 3Bot connect app [v1.3.2]

### ISSUE THREAD

**Issue by MathiasDeWeerdt** [threefoldtech/3Bot_connect#6]
Make sure the app shows '3Bot connect' on the front page.
Rename Pages => Threefold News Circles
Rename Pay => Wallet
Remove circles

**Comment by coeneivan** [comment]
This will make it easier to keep track 
- [ ] Make sure the app shows '3Bot connect' on the front page.
- [ ] Rename Pages => Threefold News Circles
- [ ] Rename Pay => Wallet
- [ ] Remove circles
