### ISSUE TITLE
When disabling background activities ( develop options ) the login flow from mobile browser to app does not work at all.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/3Bot_connect#65]
**Repro steps**
1) Go to dev settings and disable background processes/activities
2) Browse to freeflowpages on mobile browser, open in app
3) Log in using the app, go back to browser

**Expected Result**
User is logged in

**Actual Result**
User is not logged in, still says open in app.

**System Info**
Happens on all versions. Both Android and iOS

**Comment by MathiasDeWeerdt** [comment]
Fixed
