### ISSUE TITLE
When trying to log in on firefox mobile, the login flow fails because the 3bot connect app opens in the browser instead of opening the app itself.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/3Bot_connect#66]
**Repro steps**
1) Open firefox browser, go to freeflowpages
2) Attempt to log in using the app
3) Return to browser

**Expected Result**
App is opened correctly, or our app redirects back to freeflowpages at the end of the process.

**Actual Result**
The app opens inside the firefox application, login flow seems to work but at the end where it tells you to go back to the browser, there is no browser to go back to.

**System Info**
Android 9

January 15, 2020
Current Version
1.4.3

**Comment by MathiasDeWeerdt** [comment]
Will move this to another issue.
