### ISSUE TITLE
Open 3bot connect app button does not work on UC Browser

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/3Bot_connect#74]
**Repro steps**
1) Open staging.freeflowpages.com in UC Browser
2) Go to login and click open 3bot connect app

**Expected Result**
App opens, login is possible and user is logged in on the browser

**Actual Result**
Open 3bot connect app button does nothing

**System Info**
Android 9

**Comment by MathiasDeWeerdt** [comment]
We can revist this on a later date, for now the user should use chrome.
