### ISSUE TITLE
When the user picks the wrong emoji, the authentication continues without clear feedback what the user should do.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/3Bot_connect#77]
**Repro steps**
1) Go to freeflowpages and sign in starting in a non mobile browser
2) Authenticate on 3bot
3) Pick the wrong emoji on purpose

**Expected Result**
1) The user gets a popup, "This is not the correct emoji, please try again using the newly provided emoji in your browser" 
 When OK is picked => the user gets the pincode again.
 When Cancel is Picked => Same reaction as when the user pressed This isn't me - Cancel and the login fails.

**Actual Result**
Pincode is asked again, emoji can be picked again. But changed without any user feedback.

**System Info**
Type: Staging 
Git user: Mathias De Weerdt 
Git branch: v1.4.4 
Git hash: 37c8bea 
Time: 08:10:19 30.01.2020

**Comment by MathiasDeWeerdt** [comment]
Fixed.
