### ISSUE TITLE
Login screens shows inconsistent information and behavior

### ISSUE THREAD

**Issue by jdelrue** [threefoldtech/3Bot_connect#8]
- Alphanumeric  -> Letters and numbers (no spaces or special symbols)
- Person can still register when hitting enter
- If you browse to login.threefold.me without 3rd party, still works WTF
- Account already exists when landing on page, before name filled in
- Account already exists when entering specials symbols

- [x] Fix 1.4
- [x] Fix 1.3

**Comment by coeneivan** [comment]
@jdelrue Why do we have to fix this on both versions? Why not only 1.3 and then merge it to 1.4 ?

**Comment by jdelrue** [comment]
If merge is doable :-)

**Comment by DylanVerstraete** [comment]
Or add it on development branch ? Since this is our new feature and fixes branch

**Comment by MathiasDeWeerdt** [comment]
**Alphanumeric -> Letters and numbers (no spaces or special symbols)**
Added this to development and added a regular expression to the name field. Users can now only type in [a-z0-9] characters in the field. 

**Person can still register when hitting enter**
This seems to be fixed. 

**Account already exists when landing on page, before name filled in**
This seems to be fixed.

**Account already exists when entering specials symbols**
This seems to be fixed. 

**If you browse to login.threefold.me without 3rd party, still works WTF**
Still open.
