### ISSUE TITLE
Edge login to freeflowpages does not work in branch dev_securityPatch 

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/3Bot_connect#83]
**Repro steps**
1) Go to staging.freeflowpages.com on edge
2) Log in using correct emoji

**Expected Result**
Logged in to freeflowpages

**Actual Result**
App notification pops up
Browser never does anything, just stays counting down the timer.

**System Info**
Type: Staging 
Git user: Mathias De Weerdt 
Git branch: dev_securityPatch 
Git hash: 20a1534 
Time: 18:06:57 14.02.2020

**Comment by MathiasDeWeerdt** [comment]
Could you provide a console log output? Since I can't test on edge.

**Comment by ken-de-moor** [comment]
![image](https://user-images.githubusercontent.com/59569757/74653115-ce316580-5187-11ea-9f48-a56aea9f9282.png)
