### ISSUE TITLE
Login attempts sometimes are delayed and get out of sync on dev_securityPatch

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/3Bot_connect#84]
**Repro steps**
1) Log in on staging.freeflowpages.com
2) Check device

**Expected Result**
Login attempt immediately pops up, please look into improving performance.
IF there is a delay, the timers should be synced

**Actual Result**
Sometimes login attempt is delayed several seconds.
When this delay happens, the timers are out of sync.

**System Info**
Type: Staging 
Git user: Mathias De Weerdt 
Git branch: dev_securityPatch 
Git hash: 20a1534 
Time: 18:06:57 14.02.2020

**Comment by ken-de-moor** [comment]
If the performance issue itself can't be fixed. I recommend instead of starting the 120 sec timer, to specifically send the endtime in the attempt. This will make sure the timers are always synced no matter what device delays happen. I've noticed discrepancies as big as 5 seconds which is very noticeable when you can see both timers tick down.

**Comment by MathiasDeWeerdt** [comment]
Fixed.
