### ISSUE TITLE
The support page does not scale correctly when the keyboard is opened. ( Both IOS and Android )

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/3Bot_connect#88]
**Repro steps**
1) Go to support page in the 3bot Connect app
2) Attempt to type a message

**Expected Result**
The layout scales correctly, the input field is fully visible and the last messages remain visible.

**Actual Result**
![84MiydATWm](https://user-images.githubusercontent.com/59569757/75977997-db678780-5edd-11ea-8db8-0f6dacf64fbc.gif)

**System Info**
Type: Staging 
Git user: Mathias De Weerdt 
Git branch: v1.5.1 
Git hash: accfd96 
Time: 17:46:59 04.03.2020

**Comment by MathiasDeWeerdt** [comment]
Scaling is mostly fixed. There's a small issue where this could possibly happen again but would require further research in the keyboard integration and webviews.
