### ISSUE TITLE
During email recovery, it is possible to use invalid mails with a tab/space after the domain.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/3Bot_connect#90]
**Repro steps**
1) Recover account using a mail with a space or tab at the end

**Expected Result**
Invalid email please provide a valid mail

**Actual Result**
Recovery works, verification mails fail.

**System Info**

**Comment by ken-de-moor** [comment]
Blocked for retesting because of https://github.com/threefoldtech/3Bot_connect/issues/111

**Comment by MathiasDeWeerdt** [comment]
Fixed.
