### ISSUE TITLE
The kyc email confirmation mail should be improved

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/3Bot_connect#93]
**Repro steps**
1) Register a new 3bot connect account
2) Check the recovery email

**Expected Result**
@KristofVanstappen 

**Actual Result**
![image](https://user-images.githubusercontent.com/59569757/78974366-1cbd0980-7b12-11ea-8bc3-3947a4e04414.png)

**System Info**

**Comment by KristofVanstappen** [comment]
Hi {{3bot.name}}

You have just created a 3bot account.

We have provided a link to verify your email address. When you click on this link, you will be taken to a page confirming your address is verified.
Without this verification, not all features will be available.

Verify my email address

Thanks,

3Bot team

**Comment by MathiasDeWeerdt** [comment]
@coeneivan Has fixed this and its already working on staging.
