### ISSUE TITLE
Iphone - Registering with an email that has a space after the .com. breaks the setting screen

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/3Bot_connect#98]
**Repro steps**
1) Register using 'ken.demoor@jimber.org '
2) Go to settings

**Expected Result**
Everything works, space is trimmed or email validation error is shown and the user has to remove the space themselves while registering.

**Actual Result**
Every time the user goes to settings, the app closes

**System Info**

**Comment by MathiasDeWeerdt** [comment]
This input is now properly sanitized. Should not happen anymore.
