### ISSUE TITLE
After recovering an account using different casing, the verify email fails

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/3Bot_connect#99]
**Repro steps**
1) create an account kendemoor.3bot using ken.demoor@jimber,org
2) recover it using Kendemoor.3bot and ken.Demoor@jimber,org

**Expected Result**
Verify works

**Actual Result**
Verification link throws a 403 error
https://login.threefold.me/verifyemail?userId=kendemoor.3bot&verificationCode=czmUqUOKtydHAbqKduKwLGuRtPtAIwHGaiveuxvaAJWUJxAnaRJYZIdzpykUFSfqBrM

**System Info**

**Comment by MathiasDeWeerdt** [comment]
Using a comma shouldn't be valid in any case, but I will assume thats a typo.
This issue has been fixed in 1.5.7 (If I am not mistaken.)
